
/**
 * @roxi/routify 2.1.2
 * File generated Sun Feb 21 2021 19:58:44 GMT+0100 (Central European Standard Time)
 */

export const __version = "2.1.2"
export const __timestamp = "2021-02-21T18:58:44.431Z"

//buildRoutes
import { buildClientTree } from "@roxi/routify/runtime/buildRoutes"

//imports


//options
export const options = {}

//tree
export const _tree = {
  "name": "_layout",
  "filepath": "/_layout.svelte",
  "root": true,
  "ownMeta": {},
  "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/_layout.svelte",
  "children": [
    {
      "isFile": true,
      "isDir": false,
      "file": "_fallback.svelte",
      "filepath": "/_fallback.svelte",
      "name": "_fallback",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/_fallback.svelte",
      "importPath": "../pages/_fallback.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": true,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/_fallback",
      "id": "__fallback",
      "component": () => import('../pages/_fallback.svelte').then(m => m.default)
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "index.svelte",
      "filepath": "/index.svelte",
      "name": "index",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/index.svelte",
      "importPath": "../pages/index.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": true,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../pages/index.svelte').then(m => m.default)
    },
    {
      "isFile": true,
      "isDir": true,
      "file": "_layout.svelte",
      "filepath": "/ionic/_layout.svelte",
      "name": "_layout",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/_layout.svelte",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "AltDetails.svelte",
          "filepath": "/ionic/AltDetails.svelte",
          "name": "AltDetails",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/AltDetails.svelte",
          "importPath": "../pages/ionic/AltDetails.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/AltDetails",
          "id": "_ionic_AltDetails",
          "component": () => import('../pages/ionic/AltDetails.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Avatars.svelte",
          "filepath": "/ionic/Avatars.svelte",
          "name": "Avatars",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Avatars.svelte",
          "importPath": "../pages/ionic/Avatars.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Avatars",
          "id": "_ionic_Avatars",
          "component": () => import('../pages/ionic/Avatars.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Badge.svelte",
          "filepath": "/ionic/Badge.svelte",
          "name": "Badge",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Badge.svelte",
          "importPath": "../pages/ionic/Badge.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Badge",
          "id": "_ionic_Badge",
          "component": () => import('../pages/ionic/Badge.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Button.svelte",
          "filepath": "/ionic/Button.svelte",
          "name": "Button",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Button.svelte",
          "importPath": "../pages/ionic/Button.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Button",
          "id": "_ionic_Button",
          "component": () => import('../pages/ionic/Button.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Card.svelte",
          "filepath": "/ionic/Card.svelte",
          "name": "Card",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Card.svelte",
          "importPath": "../pages/ionic/Card.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Card",
          "id": "_ionic_Card",
          "component": () => import('../pages/ionic/Card.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Checkbox.svelte",
          "filepath": "/ionic/Checkbox.svelte",
          "name": "Checkbox",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Checkbox.svelte",
          "importPath": "../pages/ionic/Checkbox.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Checkbox",
          "id": "_ionic_Checkbox",
          "component": () => import('../pages/ionic/Checkbox.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Chip.svelte",
          "filepath": "/ionic/Chip.svelte",
          "name": "Chip",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Chip.svelte",
          "importPath": "../pages/ionic/Chip.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Chip",
          "id": "_ionic_Chip",
          "component": () => import('../pages/ionic/Chip.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Controllers.svelte",
          "filepath": "/ionic/Controllers.svelte",
          "name": "Controllers",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Controllers.svelte",
          "importPath": "../pages/ionic/Controllers.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Controllers",
          "id": "_ionic_Controllers",
          "component": () => import('../pages/ionic/Controllers.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Datetime.svelte",
          "filepath": "/ionic/Datetime.svelte",
          "name": "Datetime",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Datetime.svelte",
          "importPath": "../pages/ionic/Datetime.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Datetime",
          "id": "_ionic_Datetime",
          "component": () => import('../pages/ionic/Datetime.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Fab.svelte",
          "filepath": "/ionic/Fab.svelte",
          "name": "Fab",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Fab.svelte",
          "importPath": "../pages/ionic/Fab.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Fab",
          "id": "_ionic_Fab",
          "component": () => import('../pages/ionic/Fab.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Games.svelte",
          "filepath": "/ionic/Games.svelte",
          "name": "Games",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Games.svelte",
          "importPath": "../pages/ionic/Games.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Games",
          "id": "_ionic_Games",
          "component": () => import('../pages/ionic/Games.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Grid.svelte",
          "filepath": "/ionic/Grid.svelte",
          "name": "Grid",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Grid.svelte",
          "importPath": "../pages/ionic/Grid.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Grid",
          "id": "_ionic_Grid",
          "component": () => import('../pages/ionic/Grid.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Icon.svelte",
          "filepath": "/ionic/Icon.svelte",
          "name": "Icon",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Icon.svelte",
          "importPath": "../pages/ionic/Icon.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Icon",
          "id": "_ionic_Icon",
          "component": () => import('../pages/ionic/Icon.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Infinitescroll.svelte",
          "filepath": "/ionic/Infinitescroll.svelte",
          "name": "Infinitescroll",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Infinitescroll.svelte",
          "importPath": "../pages/ionic/Infinitescroll.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Infinitescroll",
          "id": "_ionic_Infinitescroll",
          "component": () => import('../pages/ionic/Infinitescroll.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Inputs.svelte",
          "filepath": "/ionic/Inputs.svelte",
          "name": "Inputs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Inputs.svelte",
          "importPath": "../pages/ionic/Inputs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Inputs",
          "id": "_ionic_Inputs",
          "component": () => import('../pages/ionic/Inputs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Item.svelte",
          "filepath": "/ionic/Item.svelte",
          "name": "Item",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Item.svelte",
          "importPath": "../pages/ionic/Item.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Item",
          "id": "_ionic_Item",
          "component": () => import('../pages/ionic/Item.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "List.svelte",
          "filepath": "/ionic/List.svelte",
          "name": "List",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/List.svelte",
          "importPath": "../pages/ionic/List.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/List",
          "id": "_ionic_List",
          "component": () => import('../pages/ionic/List.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ModalExtra.svelte",
          "filepath": "/ionic/ModalExtra.svelte",
          "name": "ModalExtra",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/ModalExtra.svelte",
          "importPath": "../pages/ionic/ModalExtra.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/ModalExtra",
          "id": "_ionic_ModalExtra",
          "component": () => import('../pages/ionic/ModalExtra.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Music.svelte",
          "filepath": "/ionic/Music.svelte",
          "name": "Music",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Music.svelte",
          "importPath": "../pages/ionic/Music.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Music",
          "id": "_ionic_Music",
          "component": () => import('../pages/ionic/Music.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Nav.svelte",
          "filepath": "/ionic/Nav.svelte",
          "name": "Nav",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Nav.svelte",
          "importPath": "../pages/ionic/Nav.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Nav",
          "id": "_ionic_Nav",
          "component": () => import('../pages/ionic/Nav.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "NavDetail.svelte",
          "filepath": "/ionic/NavDetail.svelte",
          "name": "NavDetail",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/NavDetail.svelte",
          "importPath": "../pages/ionic/NavDetail.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/NavDetail",
          "id": "_ionic_NavDetail",
          "component": () => import('../pages/ionic/NavDetail.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "NavList.svelte",
          "filepath": "/ionic/NavList.svelte",
          "name": "NavList",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/NavList.svelte",
          "importPath": "../pages/ionic/NavList.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/NavList",
          "id": "_ionic_NavList",
          "component": () => import('../pages/ionic/NavList.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Note.svelte",
          "filepath": "/ionic/Note.svelte",
          "name": "Note",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Note.svelte",
          "importPath": "../pages/ionic/Note.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Note",
          "id": "_ionic_Note",
          "component": () => import('../pages/ionic/Note.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Pane.svelte",
          "filepath": "/ionic/Pane.svelte",
          "name": "Pane",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Pane.svelte",
          "importPath": "../pages/ionic/Pane.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Pane",
          "id": "_ionic_Pane",
          "component": () => import('../pages/ionic/Pane.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "PopoverExtra.svelte",
          "filepath": "/ionic/PopoverExtra.svelte",
          "name": "PopoverExtra",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/PopoverExtra.svelte",
          "importPath": "../pages/ionic/PopoverExtra.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/PopoverExtra",
          "id": "_ionic_PopoverExtra",
          "component": () => import('../pages/ionic/PopoverExtra.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ProgressBar.svelte",
          "filepath": "/ionic/ProgressBar.svelte",
          "name": "ProgressBar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/ProgressBar.svelte",
          "importPath": "../pages/ionic/ProgressBar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/ProgressBar",
          "id": "_ionic_ProgressBar",
          "component": () => import('../pages/ionic/ProgressBar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Radio.svelte",
          "filepath": "/ionic/Radio.svelte",
          "name": "Radio",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Radio.svelte",
          "importPath": "../pages/ionic/Radio.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Radio",
          "id": "_ionic_Radio",
          "component": () => import('../pages/ionic/Radio.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Range.svelte",
          "filepath": "/ionic/Range.svelte",
          "name": "Range",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Range.svelte",
          "importPath": "../pages/ionic/Range.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Range",
          "id": "_ionic_Range",
          "component": () => import('../pages/ionic/Range.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Refresher.svelte",
          "filepath": "/ionic/Refresher.svelte",
          "name": "Refresher",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Refresher.svelte",
          "importPath": "../pages/ionic/Refresher.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Refresher",
          "id": "_ionic_Refresher",
          "component": () => import('../pages/ionic/Refresher.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Reorder.svelte",
          "filepath": "/ionic/Reorder.svelte",
          "name": "Reorder",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Reorder.svelte",
          "importPath": "../pages/ionic/Reorder.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Reorder",
          "id": "_ionic_Reorder",
          "component": () => import('../pages/ionic/Reorder.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Searchbar.svelte",
          "filepath": "/ionic/Searchbar.svelte",
          "name": "Searchbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Searchbar.svelte",
          "importPath": "../pages/ionic/Searchbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Searchbar",
          "id": "_ionic_Searchbar",
          "component": () => import('../pages/ionic/Searchbar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Segment.svelte",
          "filepath": "/ionic/Segment.svelte",
          "name": "Segment",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Segment.svelte",
          "importPath": "../pages/ionic/Segment.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Segment",
          "id": "_ionic_Segment",
          "component": () => import('../pages/ionic/Segment.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Select.svelte",
          "filepath": "/ionic/Select.svelte",
          "name": "Select",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Select.svelte",
          "importPath": "../pages/ionic/Select.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Select",
          "id": "_ionic_Select",
          "component": () => import('../pages/ionic/Select.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Skeleton.svelte",
          "filepath": "/ionic/Skeleton.svelte",
          "name": "Skeleton",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Skeleton.svelte",
          "importPath": "../pages/ionic/Skeleton.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Skeleton",
          "id": "_ionic_Skeleton",
          "component": () => import('../pages/ionic/Skeleton.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Slides.svelte",
          "filepath": "/ionic/Slides.svelte",
          "name": "Slides",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Slides.svelte",
          "importPath": "../pages/ionic/Slides.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Slides",
          "id": "_ionic_Slides",
          "component": () => import('../pages/ionic/Slides.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Spinner.svelte",
          "filepath": "/ionic/Spinner.svelte",
          "name": "Spinner",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Spinner.svelte",
          "importPath": "../pages/ionic/Spinner.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Spinner",
          "id": "_ionic_Spinner",
          "component": () => import('../pages/ionic/Spinner.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Splash.svelte",
          "filepath": "/ionic/Splash.svelte",
          "name": "Splash",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Splash.svelte",
          "importPath": "../pages/ionic/Splash.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Splash",
          "id": "_ionic_Splash",
          "component": () => import('../pages/ionic/Splash.svelte').then(m => m.default)
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "tabs",
          "filepath": "/ionic/tabs",
          "name": "tabs",
          "ext": "",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/tabs",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "[tab].svelte",
              "filepath": "/ionic/tabs/[tab].svelte",
              "name": "[tab]",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/tabs/[tab].svelte",
              "importPath": "../pages/ionic/tabs/[tab].svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/ionic/tabs/:tab",
              "id": "_ionic_tabs__tab",
              "component": () => import('../pages/ionic/tabs/[tab].svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/tabs"
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Text.svelte",
          "filepath": "/ionic/Text.svelte",
          "name": "Text",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Text.svelte",
          "importPath": "../pages/ionic/Text.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Text",
          "id": "_ionic_Text",
          "component": () => import('../pages/ionic/Text.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Thumbnails.svelte",
          "filepath": "/ionic/Thumbnails.svelte",
          "name": "Thumbnails",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Thumbnails.svelte",
          "importPath": "../pages/ionic/Thumbnails.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Thumbnails",
          "id": "_ionic_Thumbnails",
          "component": () => import('../pages/ionic/Thumbnails.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Timeline.svelte",
          "filepath": "/ionic/Timeline.svelte",
          "name": "Timeline",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Timeline.svelte",
          "importPath": "../pages/ionic/Timeline.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Timeline",
          "id": "_ionic_Timeline",
          "component": () => import('../pages/ionic/Timeline.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toggle.svelte",
          "filepath": "/ionic/Toggle.svelte",
          "name": "Toggle",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Toggle.svelte",
          "importPath": "../pages/ionic/Toggle.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Toggle",
          "id": "_ionic_Toggle",
          "component": () => import('../pages/ionic/Toggle.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toolbar.svelte",
          "filepath": "/ionic/Toolbar.svelte",
          "name": "Toolbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/ionic/Toolbar.svelte",
          "importPath": "../pages/ionic/Toolbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Toolbar",
          "id": "_ionic_Toolbar",
          "component": () => import('../pages/ionic/Toolbar.svelte').then(m => m.default)
        }
      ],
      "isLayout": true,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "importPath": "../pages/ionic/_layout.svelte",
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/ionic",
      "id": "_ionic__layout",
      "component": () => import('../pages/ionic/_layout.svelte').then(m => m.default)
    }
  ],
  "isLayout": true,
  "isReset": false,
  "isIndex": false,
  "isFallback": false,
  "isPage": false,
  "isFile": true,
  "file": "_layout.svelte",
  "ext": "svelte",
  "badExt": false,
  "importPath": "../pages/_layout.svelte",
  "meta": {
    "preload": false,
    "prerender": true,
    "precache-order": false,
    "precache-proximity": true,
    "recursive": true
  },
  "path": "/",
  "id": "__layout",
  "component": () => import('../pages/_layout.svelte').then(m => m.default)
}


export const {tree, routes} = buildClientTree(_tree)

