
/**
 * @roxi/routify 2.0.0
 * File generated Sun Sep 06 2020 17:24:15 GMT+0200 (Central European Summer Time)
 */

export const __version = "2.0.0"
export const __timestamp = "2020-09-06T15:24:15.885Z"

//buildRoutes
import { buildClientTree } from "@roxi/routify/runtime/buildRoutes"

//imports


//options
export const options = {}

//tree
export const _tree = {
  "name": "_layout",
  "filepath": "/_layout.svelte",
  "root": true,
  "ownMeta": {},
  "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/_layout.svelte",
  "children": [
    {
      "isFile": true,
      "isDir": false,
      "file": "_fallback.svelte",
      "filepath": "/_fallback.svelte",
      "name": "_fallback",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/_fallback.svelte",
      "importPath": "../pages/_fallback.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": true,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/_fallback",
      "id": "__fallback",
      "component": () => import('../pages/_fallback.svelte').then(m => m.default)
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "index.svelte",
      "filepath": "/index.svelte",
      "name": "index",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/index.svelte",
      "importPath": "../pages/index.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": true,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../pages/index.svelte').then(m => m.default)
    },
    {
      "isFile": true,
      "isDir": true,
      "file": "_layout.svelte",
      "filepath": "/ionic/_layout.svelte",
      "name": "_layout",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/_layout.svelte",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "AltDetails.svelte",
          "filepath": "/ionic/AltDetails.svelte",
          "name": "AltDetails",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/AltDetails.svelte",
          "importPath": "../pages/ionic/AltDetails.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/AltDetails",
          "id": "_ionic_AltDetails",
          "component": () => import('../pages/ionic/AltDetails.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Avatars.svelte",
          "filepath": "/ionic/Avatars.svelte",
          "name": "Avatars",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Avatars.svelte",
          "importPath": "../pages/ionic/Avatars.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Avatars",
          "id": "_ionic_Avatars",
          "component": () => import('../pages/ionic/Avatars.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Badges.svelte",
          "filepath": "/ionic/Badges.svelte",
          "name": "Badges",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Badges.svelte",
          "importPath": "../pages/ionic/Badges.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Badges",
          "id": "_ionic_Badges",
          "component": () => import('../pages/ionic/Badges.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Buttons.svelte",
          "filepath": "/ionic/Buttons.svelte",
          "name": "Buttons",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Buttons.svelte",
          "importPath": "../pages/ionic/Buttons.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Buttons",
          "id": "_ionic_Buttons",
          "component": () => import('../pages/ionic/Buttons.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Cards.svelte",
          "filepath": "/ionic/Cards.svelte",
          "name": "Cards",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Cards.svelte",
          "importPath": "../pages/ionic/Cards.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Cards",
          "id": "_ionic_Cards",
          "component": () => import('../pages/ionic/Cards.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Checkboxes.svelte",
          "filepath": "/ionic/Checkboxes.svelte",
          "name": "Checkboxes",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Checkboxes.svelte",
          "importPath": "../pages/ionic/Checkboxes.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Checkboxes",
          "id": "_ionic_Checkboxes",
          "component": () => import('../pages/ionic/Checkboxes.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Chips.svelte",
          "filepath": "/ionic/Chips.svelte",
          "name": "Chips",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Chips.svelte",
          "importPath": "../pages/ionic/Chips.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Chips",
          "id": "_ionic_Chips",
          "component": () => import('../pages/ionic/Chips.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Controllers.svelte",
          "filepath": "/ionic/Controllers.svelte",
          "name": "Controllers",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Controllers.svelte",
          "importPath": "../pages/ionic/Controllers.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Controllers",
          "id": "_ionic_Controllers",
          "component": () => import('../pages/ionic/Controllers.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Datetime.svelte",
          "filepath": "/ionic/Datetime.svelte",
          "name": "Datetime",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Datetime.svelte",
          "importPath": "../pages/ionic/Datetime.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Datetime",
          "id": "_ionic_Datetime",
          "component": () => import('../pages/ionic/Datetime.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Fabs.svelte",
          "filepath": "/ionic/Fabs.svelte",
          "name": "Fabs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Fabs.svelte",
          "importPath": "../pages/ionic/Fabs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Fabs",
          "id": "_ionic_Fabs",
          "component": () => import('../pages/ionic/Fabs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Games.svelte",
          "filepath": "/ionic/Games.svelte",
          "name": "Games",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Games.svelte",
          "importPath": "../pages/ionic/Games.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Games",
          "id": "_ionic_Games",
          "component": () => import('../pages/ionic/Games.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Grid.svelte",
          "filepath": "/ionic/Grid.svelte",
          "name": "Grid",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Grid.svelte",
          "importPath": "../pages/ionic/Grid.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Grid",
          "id": "_ionic_Grid",
          "component": () => import('../pages/ionic/Grid.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Icons.svelte",
          "filepath": "/ionic/Icons.svelte",
          "name": "Icons",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Icons.svelte",
          "importPath": "../pages/ionic/Icons.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Icons",
          "id": "_ionic_Icons",
          "component": () => import('../pages/ionic/Icons.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Infinitescroll.svelte",
          "filepath": "/ionic/Infinitescroll.svelte",
          "name": "Infinitescroll",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Infinitescroll.svelte",
          "importPath": "../pages/ionic/Infinitescroll.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Infinitescroll",
          "id": "_ionic_Infinitescroll",
          "component": () => import('../pages/ionic/Infinitescroll.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Inputs.svelte",
          "filepath": "/ionic/Inputs.svelte",
          "name": "Inputs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Inputs.svelte",
          "importPath": "../pages/ionic/Inputs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Inputs",
          "id": "_ionic_Inputs",
          "component": () => import('../pages/ionic/Inputs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Items.svelte",
          "filepath": "/ionic/Items.svelte",
          "name": "Items",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Items.svelte",
          "importPath": "../pages/ionic/Items.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Items",
          "id": "_ionic_Items",
          "component": () => import('../pages/ionic/Items.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Lists.svelte",
          "filepath": "/ionic/Lists.svelte",
          "name": "Lists",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Lists.svelte",
          "importPath": "../pages/ionic/Lists.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Lists",
          "id": "_ionic_Lists",
          "component": () => import('../pages/ionic/Lists.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ModalExtra.svelte",
          "filepath": "/ionic/ModalExtra.svelte",
          "name": "ModalExtra",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/ModalExtra.svelte",
          "importPath": "../pages/ionic/ModalExtra.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/ModalExtra",
          "id": "_ionic_ModalExtra",
          "component": () => import('../pages/ionic/ModalExtra.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Music.svelte",
          "filepath": "/ionic/Music.svelte",
          "name": "Music",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Music.svelte",
          "importPath": "../pages/ionic/Music.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Music",
          "id": "_ionic_Music",
          "component": () => import('../pages/ionic/Music.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Nav.svelte",
          "filepath": "/ionic/Nav.svelte",
          "name": "Nav",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Nav.svelte",
          "importPath": "../pages/ionic/Nav.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Nav",
          "id": "_ionic_Nav",
          "component": () => import('../pages/ionic/Nav.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "NavDetail.svelte",
          "filepath": "/ionic/NavDetail.svelte",
          "name": "NavDetail",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/NavDetail.svelte",
          "importPath": "../pages/ionic/NavDetail.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/NavDetail",
          "id": "_ionic_NavDetail",
          "component": () => import('../pages/ionic/NavDetail.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "NavList.svelte",
          "filepath": "/ionic/NavList.svelte",
          "name": "NavList",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/NavList.svelte",
          "importPath": "../pages/ionic/NavList.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/NavList",
          "id": "_ionic_NavList",
          "component": () => import('../pages/ionic/NavList.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Notes.svelte",
          "filepath": "/ionic/Notes.svelte",
          "name": "Notes",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Notes.svelte",
          "importPath": "../pages/ionic/Notes.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Notes",
          "id": "_ionic_Notes",
          "component": () => import('../pages/ionic/Notes.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Pane.svelte",
          "filepath": "/ionic/Pane.svelte",
          "name": "Pane",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Pane.svelte",
          "importPath": "../pages/ionic/Pane.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Pane",
          "id": "_ionic_Pane",
          "component": () => import('../pages/ionic/Pane.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "PopoverExtra.svelte",
          "filepath": "/ionic/PopoverExtra.svelte",
          "name": "PopoverExtra",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/PopoverExtra.svelte",
          "importPath": "../pages/ionic/PopoverExtra.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/PopoverExtra",
          "id": "_ionic_PopoverExtra",
          "component": () => import('../pages/ionic/PopoverExtra.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ProgressBar.svelte",
          "filepath": "/ionic/ProgressBar.svelte",
          "name": "ProgressBar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/ProgressBar.svelte",
          "importPath": "../pages/ionic/ProgressBar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/ProgressBar",
          "id": "_ionic_ProgressBar",
          "component": () => import('../pages/ionic/ProgressBar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Radios.svelte",
          "filepath": "/ionic/Radios.svelte",
          "name": "Radios",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Radios.svelte",
          "importPath": "../pages/ionic/Radios.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Radios",
          "id": "_ionic_Radios",
          "component": () => import('../pages/ionic/Radios.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Range.svelte",
          "filepath": "/ionic/Range.svelte",
          "name": "Range",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Range.svelte",
          "importPath": "../pages/ionic/Range.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Range",
          "id": "_ionic_Range",
          "component": () => import('../pages/ionic/Range.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Refresher.svelte",
          "filepath": "/ionic/Refresher.svelte",
          "name": "Refresher",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Refresher.svelte",
          "importPath": "../pages/ionic/Refresher.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Refresher",
          "id": "_ionic_Refresher",
          "component": () => import('../pages/ionic/Refresher.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Reorder.svelte",
          "filepath": "/ionic/Reorder.svelte",
          "name": "Reorder",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Reorder.svelte",
          "importPath": "../pages/ionic/Reorder.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Reorder",
          "id": "_ionic_Reorder",
          "component": () => import('../pages/ionic/Reorder.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Searchbar.svelte",
          "filepath": "/ionic/Searchbar.svelte",
          "name": "Searchbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Searchbar.svelte",
          "importPath": "../pages/ionic/Searchbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Searchbar",
          "id": "_ionic_Searchbar",
          "component": () => import('../pages/ionic/Searchbar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Segment.svelte",
          "filepath": "/ionic/Segment.svelte",
          "name": "Segment",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Segment.svelte",
          "importPath": "../pages/ionic/Segment.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Segment",
          "id": "_ionic_Segment",
          "component": () => import('../pages/ionic/Segment.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Select.svelte",
          "filepath": "/ionic/Select.svelte",
          "name": "Select",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Select.svelte",
          "importPath": "../pages/ionic/Select.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Select",
          "id": "_ionic_Select",
          "component": () => import('../pages/ionic/Select.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Skeleton.svelte",
          "filepath": "/ionic/Skeleton.svelte",
          "name": "Skeleton",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Skeleton.svelte",
          "importPath": "../pages/ionic/Skeleton.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Skeleton",
          "id": "_ionic_Skeleton",
          "component": () => import('../pages/ionic/Skeleton.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Slides.svelte",
          "filepath": "/ionic/Slides.svelte",
          "name": "Slides",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Slides.svelte",
          "importPath": "../pages/ionic/Slides.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Slides",
          "id": "_ionic_Slides",
          "component": () => import('../pages/ionic/Slides.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Spinner.svelte",
          "filepath": "/ionic/Spinner.svelte",
          "name": "Spinner",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Spinner.svelte",
          "importPath": "../pages/ionic/Spinner.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Spinner",
          "id": "_ionic_Spinner",
          "component": () => import('../pages/ionic/Spinner.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Splash.svelte",
          "filepath": "/ionic/Splash.svelte",
          "name": "Splash",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Splash.svelte",
          "importPath": "../pages/ionic/Splash.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Splash",
          "id": "_ionic_Splash",
          "component": () => import('../pages/ionic/Splash.svelte').then(m => m.default)
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "tabs",
          "filepath": "/ionic/tabs",
          "name": "tabs",
          "ext": "",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/tabs",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "[tab].svelte",
              "filepath": "/ionic/tabs/[tab].svelte",
              "name": "[tab]",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/tabs/[tab].svelte",
              "importPath": "../pages/ionic/tabs/[tab].svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/ionic/tabs/:tab",
              "id": "_ionic_tabs__tab",
              "component": () => import('../pages/ionic/tabs/[tab].svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/tabs"
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Text.svelte",
          "filepath": "/ionic/Text.svelte",
          "name": "Text",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Text.svelte",
          "importPath": "../pages/ionic/Text.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Text",
          "id": "_ionic_Text",
          "component": () => import('../pages/ionic/Text.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Thumbnails.svelte",
          "filepath": "/ionic/Thumbnails.svelte",
          "name": "Thumbnails",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Thumbnails.svelte",
          "importPath": "../pages/ionic/Thumbnails.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Thumbnails",
          "id": "_ionic_Thumbnails",
          "component": () => import('../pages/ionic/Thumbnails.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Timeline.svelte",
          "filepath": "/ionic/Timeline.svelte",
          "name": "Timeline",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Timeline.svelte",
          "importPath": "../pages/ionic/Timeline.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Timeline",
          "id": "_ionic_Timeline",
          "component": () => import('../pages/ionic/Timeline.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toggle.svelte",
          "filepath": "/ionic/Toggle.svelte",
          "name": "Toggle",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Toggle.svelte",
          "importPath": "../pages/ionic/Toggle.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Toggle",
          "id": "_ionic_Toggle",
          "component": () => import('../pages/ionic/Toggle.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toolbar.svelte",
          "filepath": "/ionic/Toolbar.svelte",
          "name": "Toolbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Gebruikers/Developer/Src/svelte-ionic-app/src/pages/ionic/Toolbar.svelte",
          "importPath": "../pages/ionic/Toolbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/ionic/Toolbar",
          "id": "_ionic_Toolbar",
          "component": () => import('../pages/ionic/Toolbar.svelte').then(m => m.default)
        }
      ],
      "isLayout": true,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "importPath": "../pages/ionic/_layout.svelte",
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/ionic",
      "id": "_ionic__layout",
      "component": () => import('../pages/ionic/_layout.svelte').then(m => m.default)
    }
  ],
  "isLayout": true,
  "isReset": false,
  "isIndex": false,
  "isFallback": false,
  "isPage": false,
  "isFile": true,
  "file": "_layout.svelte",
  "ext": "svelte",
  "badExt": false,
  "importPath": "../pages/_layout.svelte",
  "meta": {
    "preload": false,
    "prerender": true,
    "precache-order": false,
    "precache-proximity": true,
    "recursive": true
  },
  "path": "/",
  "id": "__layout",
  "component": () => import('../pages/_layout.svelte').then(m => m.default)
}


export const {tree, routes} = buildClientTree(_tree)

