<ion-card class="act-card" _value="act-card">
  <ion-card-header>
    <ion-card-subtitle>
      {name.title}`{name.first}
      {name.last}`
    </ion-card-subtitle>
    <ion-card-title>{title}</ion-card-title>
  </ion-card-header>
  <ion-card-content ion-padding>
    <ion-col>
      {description}
     
    </ion-col>
  </ion-card-content>
  <ion-card-footer>
    <ion-button fill="clear">
      <ion-icon slot="icon-only" ios="heart" md="heart-sharp"></ion-icon>
    </ion-button>
    <ion-button fill="clear">
      <ion-icon slot="icon-only" ios="share" md="share-sharp"></ion-icon>
    </ion-button>
    <ion-chip>
      <ion-avatar><img alt="avatar" src="{picture.thumbnail}" /></ion-avatar>
      <ion-label>Avatar</ion-label>
    </ion-chip>
  </ion-card-footer>
</ion-card>

<style>

</style>

<script>
import * as faker from 'faker';



export let pdf;
export let vdo;
export const rating = (Math.random()*5);
export let name;
export let picture;

export let title = faker.commerce.product()
export let description=faker.lorem.sentences()

async function generate() {

}

(pdf =
  "https://drive.google.com/file/d/11lm2ilKjqsR6o8TLvgtSNya_WnQCukxN/view?usp=sharing"),
  //  pdf="https://drive.google.com/file/d/1GftRML3WKz9x15UI-REOqLG3DDPK4lTS/view?usp=sharing",
  // https://drive.google.com/file/d/1eRPbl7LD__5TORoHnlpNgA054yX4V76Y/view?usp=sharing
  (vdo =
    "https://drive.google.com/file/d/11lm2ilKjqsR6o8TLvgtSNya_WnQCukxN/view?usp=sharing");
//   https://drive.google.com/file/d/1B1SnwQq4wUO4pbR0WSQPRy19fwecGr3e/view?usp=sharing


// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
</script>
